### ISSUE TITLE
Parameter table render problem when parameter has multiple types

### ISSUE THREAD

**Issue by wachri** [tgreyjs/typedoc-plugin-markdown#27]
If you have a function or method like with a parameter with multiple types like
```
function doOtherThings(value: string | number | SubClassA): void {} 
```
the table isn't rendered correct:

| Param | Type | Description |
| ------ | ------ | ------ |
| value | `string` |
`number` |
`ElementFinder`
 |  A description |

The output is:
```
| Param | Type | Description |
| ------ | ------ | ------ |
| value | `string` |
`number` |
`ElementFinder`
 |  A description |
```

I'm already working on a PR.

**Comment by tgreyjs** [comment]
Thanks for raising and for the PR. Available in 1.1.9.
