### ISSUE TITLE
Node v6 support removed?

### ISSUE THREAD

**Issue by tehsenaus** [tgreyjs/typedoc-plugin-markdown#32]
It appears this commit broke my build, as yarn will now refuse to install the package on node v6:
https://github.com/tgreyjs/typedoc-plugin-markdown/commit/855342f4fc008cecb071e6d536749a897778cbfb

Any reason why node 6 isn't supported anymore? Shouldn't this have been a breaking change, semver-wise?

**Comment by tgreyjs** [comment]
Apologies - node 6 is supported have updated the package accordingly.

**Comment by tehsenaus** [comment]
Thanks! Appreciate the quick fix.
